/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author Frederico
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_RecursosHumanos = new javax.swing.JMenu();
        jCheckBox_CadastrarFuncionario = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxExcluirFuncionario = new javax.swing.JCheckBoxMenuItem();
        jCheckBox_Bonificacao = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_RecursosHumanos.setText("Recursos Humanos");

        jCheckBox_CadastrarFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBox_CadastrarFuncionario.setSelected(true);
        jCheckBox_CadastrarFuncionario.setText("Cadastrar Funcionário");
        jCheckBox_CadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu_RecursosHumanos.add(jCheckBox_CadastrarFuncionario);

        jCheckBoxExcluirFuncionario.setSelected(true);
        jCheckBoxExcluirFuncionario.setText("Excluir funcionário");
        jCheckBoxExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExcluirFuncionarioActionPerformed(evt);
            }
        });
        jMenu_RecursosHumanos.add(jCheckBoxExcluirFuncionario);

        jCheckBox_Bonificacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBox_Bonificacao.setSelected(true);
        jCheckBox_Bonificacao.setText("Bonificação");
        jCheckBox_Bonificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BonificacaoActionPerformed(evt);
            }
        });
        jMenu_RecursosHumanos.add(jCheckBox_Bonificacao);

        jMenuBar1.add(jMenu_RecursosHumanos);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1040, 583);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_CadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CadastrarFuncionarioActionPerformed
        CadastroDeFuncionarios acesso = new CadastroDeFuncionarios();
        acesso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBox_CadastrarFuncionarioActionPerformed

    private void jCheckBoxExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExcluirFuncionarioActionPerformed
        ExcluirFuncionario acesso = new ExcluirFuncionario();
        acesso.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jCheckBoxExcluirFuncionarioActionPerformed

    private void jCheckBox_BonificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BonificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_BonificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxExcluirFuncionario;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBox_Bonificacao;
    private javax.swing.JCheckBoxMenuItem jCheckBox_CadastrarFuncionario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenu_RecursosHumanos;
    // End of variables declaration//GEN-END:variables
}
