package Telas;

import Conexao.ConexaoMySQL;
import Rh.Cargos.Administrador;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Frederico
 */
public class TelaDeLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeLogin
     */
    public TelaDeLogin() { //Inicialização de todos os componentes do Form.
        initComponents();

        Connection conexao = ConexaoMySQL.conector();

        if (conexao != null) {
            Lbl_Status.setText("Conectado");
        } else {
            Lbl_Status.setText("Desconectado");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Txt_Nome = new javax.swing.JTextField();
        Lbl_Nome = new javax.swing.JLabel();
        Lbl_Senha = new javax.swing.JLabel();
        Txt_Senha = new javax.swing.JTextField();
        Lbl_Status = new javax.swing.JLabel();
        Button_Entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txt_Nome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        Lbl_Nome.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Lbl_Nome.setText("Nome: ");

        Lbl_Senha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Lbl_Senha.setText("Senha:");

        Txt_Senha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        Lbl_Status.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Lbl_Status.setText("Status");

        Button_Entrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Button_Entrar.setText("Entrar");
        Button_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_Entrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Senha)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_Senha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lbl_Nome)
                        .addGap(18, 18, 18)
                        .addComponent(Txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Nome))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Senha)
                    .addComponent(Txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_Status)
                    .addComponent(Button_Entrar))
                .addGap(159, 159, 159))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EntrarActionPerformed

        try {
            // codificação do botão entrar.
            String nome = Txt_Nome.getText();
            String senha = Txt_Senha.getText();

            Administrador adm = new Administrador();
            adm.setNomeAdm(nome);
            adm.setSenhaAdm(senha);

            ResultSet resultadoConexaoAdm = adm.autenticacaoAdministrador(adm);

            if (resultadoConexaoAdm.next()) {
                //chamar tela que eu quero abrir
                Menu acesso = new Menu();
                acesso.setVisible(true);
                dispose();//fecha a tela atual
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválida.");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro no form TelaDeLogin: " + erro);
        }

    }//GEN-LAST:event_Button_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Entrar;
    private javax.swing.JLabel Lbl_Nome;
    private javax.swing.JLabel Lbl_Senha;
    private javax.swing.JLabel Lbl_Status;
    private javax.swing.JTextField Txt_Nome;
    private javax.swing.JTextField Txt_Senha;
    // End of variables declaration//GEN-END:variables
}
